### ISSUE TITLE
vanX: `TypeError: 'get' on proxy` and `TypeError: 'set' on proxy`, what am I doing wrong?

### ISSUE THREAD

**Issue by metaleap** [vanjs-org/van#148]
Here's my dummy .ts component:

```typescript
import van from '../../__yostatic/vanjs/van-1.2.3.debug.js'
import * as vanx from '../../__yostatic/vanjs/van-x.js'
import * as yo from '../yo-sdk.js'

const htm = van.tags

export type UiCtlBuddies = {
    DOM: HTMLElement
    buddies: vanx.Reactive<yo.User[]> // User type def not included here, the inits below show it anyway
}

export function create(): UiCtlBuddies {
    const me: UiCtlBuddies = {
        DOM: htm.div({ 'class': 'buddies' }),
        buddies: vanx.reactive([
            { Id: 1234, Btw: "Btw 1234", Nick: "user1234", PicFileId: "", Auth: 1234 } as yo.User,
            { Id: 2345, Btw: "Btw 2345", Nick: "user2345", PicFileId: "", Auth: 2345 } as yo.User,
            { Id: 4321, Btw: "Btw 4321", Nick: "user4321", PicFileId: "", Auth: 4321 } as yo.User,
        ])
    }

    setInterval(() => {
        const idx = Math.floor(me.buddies.length * Math.random())
        const buddy = me.buddies[idx]
        buddy.Btw = new Date().toLocaleTimeString() // take this line out and there are no errors (because there are no updates=)
    }, 1000)

    van.add(me.DOM, vanx.list(htm.ul, me.buddies, (it) => {
        const buddy = it.val
        return htm.li({}, buddy.Nick, buddy.LastSeen, buddy.Btw)
    }))

    return me
}
```

Every second, it aims to pick a random `User` in `buddies` and set its `Btw: string` to current time.

With that, every second Chrome dev-tools console spits out 2 errors together, first:

> Uncaught TypeError: 'set' on proxy: trap returned truish for property 'Btw' which exists in the proxy target as a non-configurable and non-writable data property with a different value
    at buddies.js:20:15
(anonymous) @ buddies.js:20

and second:

> van-1.2.3.js:17 TypeError: 'get' on proxy: property 'Btw' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'Btw 4321' but got '9:35:37 AM')
    at buddies.js:24:57
    at van-x.js:52:13
    at van-1.2.3.debug.js:60:27
    at runAndCaptureDeps (van-1.2.3.js:15:12)
    at bind (van-1.2.3.js:74:16)
    at updateDoms (van-1.2.3.js:128:20)

Any ideas what I'm doing wrong? I thought I'd basically followed the vanjs.org/x examples.. somewhere must have messed up there tho.

**Comment by Tao-VanJS** [comment]
I guess the issue might be in `van.debug.js`. Somehow `van.debug.js` is not compatible with VanX. Can you try to import `van.js` instead of `van.debug.js` to see if it resolves the problem? If so I can do a VanJS release to fix  the problem in `van.debug.js`.

**Comment by metaleap** [comment]
Good news, you had the right hunch, it works this way! Thanks! Feel free to close issue unless you want to keep it for some `.debug.js` fixup or sth  =)

**Comment by Tao-VanJS** [comment]
@all-contributors please add @metaleap for bug
